### ISSUE TITLE
Lastest version of Breakdancer depends on `react-native`

### ISSUE THREAD

**Issue by fabiomcosta** [godaddy/breakdancer#11]
The latest version of `breakdance` added `react-native` as a peer dependency.
Given `breakdance` supports both web and react-native "platforms" (AFAIK), I'd say this dependency is not desired.
Another issue is that version 0.46.1 of `react-native` requires [`react` 0.16.x](https://github.com/facebook/react-native/blob/v0.46.1/package.json#L136) and `react` version 0.15.x was also added as a peer dependency of `breakdance`, which causes issues while installing it anyway.

I honestly don't know, off the top of my head, the right solution to make `breakdancer` support RN while not forcing users of the library to have to depend on it, I'm not very experienced with projects that support both platforms, but I'd love to help with a PR if a good solution is suggested.

**Comment by indexzero** [comment]
I am pro moving it to `devDependencies` with some additional copy in `README.md` about using this package with `react-native`. 

We've gone that way with other packages (as opposed to `devDependencies` and `peerDependencies`) since `npm@3` will not provide valid `npm shrinkwrap` with unmet `peerDependencies`. An investigation into this in an `npm@5` world is prudent to update the practice. 

@fabiomcosta are you using `npm@3` or `npm@5`?

**Comment by fabiomcosta** [comment]
@indexzero We use npm@4 ATM.
To clarify, are you suggesting to just remove it from `peerDependencies`? That should work fine for web.

**Comment by indexzero** [comment]
Yes, that is what I am suggesting. Any PR making this change must include new documentation in `README.md` specifying that `react-native` is an implicit peer dependency for `react-native` scenarios.
